version: '3'

volumes:
  pg_data:
  static_volume:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
  backend:
    image: aamok/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy
  frontend:
    env_file: .env
    image: aamok/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: aamok/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_volume:/staticfiles/
      - media:/media
    depends_on:
      - backend
      - frontend