volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  backend:
    image: aamok/kittygram_backend:latest
    volumes:
      - static:/app/collected_static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  frontend:
    image: aamok/kittygram_frontend:latest
    volumes:
      - static:/app/collected_staticstatic 
    depends_on:
      - backend
    restart: always

  gateway:
    image: aamok/kittygram_gateway:latest
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
    restart: always