volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRESQL_EFFECTIVE_CACHE_SIZE: 96MB
      POSTGRESQL_SHARED_BUFFERS: 64MB
    deploy:
      resources:
        limits:
          memory: 96M

  backend:
    image: aamok/kittygram_backend:latest
    volumes:
      - static:/app/collected_static
      - media:/app/media
    env_file:
      - .env
    environment:
      GUNICORN_CMD_ARGS: "--workers=1 --threads=2"
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - db

  frontend:
    image: aamok/kittygram_frontend:latest
    volumes:
      - static:/app/collected_static
    deploy:
      resources:
        limits:
          memory: 24M

  gateway:
    image: aamok/kittygram_gateway:latest
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    deploy:
      resources:
        limits:
          memory: 26M